CREATE SCHEMA users;
CREATE TABLE users (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL UNIQUE,
    salary DECIMAL(19,5) NOT NULL
    -- created_at TIMESTAMP NOT NULL DEFAULT now(),
    -- updated_at TIMESTAMP NOT NULL DEFAULT now()
);